#!/bin/bash
# =============================================================================
# Start a LOCAL SearXNG metasearch container for the search_web tool.
#
# Aeon is local-only: the agent queries THIS container, which aggregates public
# search engines (DuckDuckGo, Brave, Google, etc.) -- there is no third-party
# search API/SaaS (e.g. Tavily) in the loop seeing or filtering queries. JSON
# output is enabled and SafeSearch is forced OFF (uncensored).
#
# The container is cheap (no GPU, ~100 MB RAM) and left running across sessions.
# Override the port with AEON_SEARXNG_PORT (default 8095).
# =============================================================================
set -e

CONTAINER_NAME="aeon_searxng"
PORT="${AEON_SEARXNG_PORT:-8095}"
AEON_HOME="${AEON_HOME:-$HOME/.aeon}"
CONFIG_DIR="$AEON_HOME/searxng"
SETTINGS="$CONFIG_DIR/settings.yml"

mkdir -p "$CONFIG_DIR"

# First run: write a minimal settings.yml that merges over SearXNG's built-in
# defaults. We only override what we need: a secret key, JSON output, SafeSearch
# off, and the bot limiter disabled (it otherwise blocks the programmatic JSON
# API and would also require a separate redis/valkey container).
if [ ! -f "$SETTINGS" ]; then
    SECRET="$(python3 -c 'import secrets; print(secrets.token_hex(32))')"
    cat > "$SETTINGS" <<EOF
# Generated by start_searxng.sh -- aeon local metasearch. Safe to edit.
use_default_settings: true
server:
  secret_key: "$SECRET"
  bind_address: "0.0.0.0"
  limiter: false
  image_proxy: false
search:
  safe_search: 0
  formats:
    - html
    - json
EOF
fi

# Already healthy? (idempotent: multiple agents may call this.)
if [ "$(curl -s -o /dev/null -w '%{http_code}' "http://localhost:${PORT}/healthz" 2>/dev/null)" = "200" ]; then
    exit 0
fi

docker rm -f "$CONTAINER_NAME" >/dev/null 2>&1 || true
docker run -d --label owner=aday --name "$CONTAINER_NAME" --restart unless-stopped \
    -p "127.0.0.1:${PORT}:8080" \
    -v "$CONFIG_DIR:/etc/searxng" \
    -e "SEARXNG_BASE_URL=http://localhost:${PORT}/" \
    searxng/searxng:latest >/dev/null

for _ in $(seq 1 40); do
    if [ "$(curl -s -o /dev/null -w '%{http_code}' "http://localhost:${PORT}/healthz" 2>/dev/null)" = "200" ]; then
        echo "[searxng] ready on 127.0.0.1:${PORT}"
        exit 0
    fi
    sleep 1
done

echo "[searxng] ERROR: container did not become healthy on :${PORT}" >&2
docker logs --tail 40 "$CONTAINER_NAME" 2>&1 || true
exit 1
